export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_NEW_TASK_TEXT = 'UPDATE_NEW_TASK_TEXT';
export const LINE_THROUGH_TASK = 'LINE_THROUGH_TASK';
export const NO_LINE_THROUGH_TASK = 'NO_LINE_THROUGH_TASK';


